### ISSUE TITLE
mcr not working

### ISSUE THREAD

**Issue by xpoveda** [pln-fing-udelar/wn-mcr-transform#3]
Hi, I have installed the mcr in python 2.7.6 and NLTK 3.0

xpoveda@ubuntu:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

I have extract the file 

xpoveda@ubuntu:~/wn-mcr-transform-master$ ls -lt wordnet_spa.tar.gz
-rw-rw-r-- 1 xpoveda xpoveda 6570399 nov  6  2014 wordnet_spa.tar.gz

in

xpoveda@ubuntu:~/nltk_data/corpora/mcrspa$ pwd
/home/xpoveda/nltk_data/corpora/mcrspa

xpoveda@ubuntu:~/nltk_data/corpora/mcrspa$ ls -lt | more
total 23908
-rw-rw-r-- 1 xpoveda xpoveda 7294043 jul 15 13:10 index.sense
-rw-rw-r-- 1 xpoveda xpoveda  361471 jul 15 13:10 index.verb
-rw-rw-r-- 1 xpoveda xpoveda     803 jul 15 13:10 lexnames
-rw-rw-r-- 1 xpoveda xpoveda   38301 jul 15 13:10 noun.exc
-rw-rw-r-- 1 xpoveda xpoveda    2296 jul 15 13:10 README.txt
-rw-rw-r-- 1 xpoveda xpoveda   38033 jul 15 13:10 verb.exc
-rw-rw-r-- 1 xpoveda xpoveda 2680782 jul 15 13:10 index.noun
-rw-rw-r-- 1 xpoveda xpoveda 8967709 jul 15 13:10 data.noun
-rw-rw-r-- 1 xpoveda xpoveda 1623527 jul 15 13:10 data.verb
-rw-rw-r-- 1 xpoveda xpoveda  485853 jul 15 13:10 index.adj
-rw-rw-r-- 1 xpoveda xpoveda  115761 jul 15 13:10 index.adv
-rw-rw-r-- 1 xpoveda xpoveda  235586 jul 15 13:10 data.adv
-rw-rw-r-- 1 xpoveda xpoveda   23019 jul 15 13:10 adj.exc
-rw-rw-r-- 1 xpoveda xpoveda      85 jul 15 13:10 adv.exc
-rw-rw-r-- 1 xpoveda xpoveda  911244 jul 15 13:10 cntlist.rev
-rw-rw-r-- 1 xpoveda xpoveda 1666095 jul 15 13:10 data.adj

but this instruction not work

=================================================
Usage:
1 - Extract the files into a folder.
2 - From a Python shell, import the NLTK library.
    >> import nltk
3 - Create a WordNet reader.
    >> wn = nltk.corpus.reader.wordnet.WordNetCorpusReader(<path to the extracted files>)

Now you can use the object wn to query the contents of MCR WordNet 3.0, for example in Spanish:
    >> print wn.synset("entidad.n.01").definition
xpoveda@ubuntu:~/nltk_data/corpora/mcrspa$ more README.txt

beacause

>>> import nltk
>>> wn = nltk.corpus.reader.wordnet.WordNetCorpusReader('/home/xpoveda/nltk_data/corpora/mcrspa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes exactly 3 arguments (2 given)
>>> 

Note: I have tried too regenerate in my ubuntu with generate_all.sh but not works too.

Can you help me?

Thanks so much!!
Xavier.

**Comment by bryant1410** [comment]
Aw, yes. There's an error there. The second argument must be None:

```python
import nltk
wn = nltk.corpus.reader.wordnet.WordNetCorpusReader('/home/xpoveda/nltk_data/corpora/mcrspa', None)

Gonna fix it

Thanks!
```

**Comment by xpoveda** [comment]
Hi Bryan, now works, but there are words in english...

by example for word "coche" (car in spanish) appears "motor_vehicle" as hypernym.
and "motor_vehicle" is a english word.

Is correct?

---

> > > import nltk
> > > wn = nltk.corpus.reader.wordnet.WordNetCorpusReader('/home/xpoveda/nltk_data/corpora/mcrspa', None)
> > > 
> > > wn.synsets('coche')
> > > [Synset('auto.n.01'), Synset('automotor.n.01'), Synset('coche.n.03')]
> > > 
> > > wn.synset('auto.n.01').lemmas()
> > > [Lemma('auto.n.01.auto'), Lemma('auto.n.01.autom\xf3vil'), Lemma('auto.n.01.carro'), Lemma('auto.n.01.coche'), Lemma('auto.n.01.m\xe1quina'), Lemma('auto.n.01.turismo'), Lemma('auto.n.01.veh\xedculo')]
> > > 
> > > wn.synset('auto.n.01').hypernyms()
> > > [Synset('`motor_vehicle.n.01')]
> > > 
> > > wn.synset('auto.n.01').hyponyms()
> > > [Synset('`ambulance.n.01'), Synset('`beach_wagon.n.01'), Synset('`compact.n.02'), Synset('`convertible.n.01'), Synset('`coupe.n.01'), Synset('`cruiser.n.02'), Synset('`electric.n.01'), Synset('`gas_guzzler.n.01'), Synset('`horseless_carriage.n.01'), Synset('`hot_rod.n.01'), Synset('`jeep.n.01'), Synset('`limousine.n.01'), Synset('`loaner.n.01'), Synset('`minicar.n.01'), Synset('`model_t.n.01'), Synset('`pace_car.n.01'), Synset('`racer.n.02'), Synset('`roadster.n.01'), Synset('`sedan.n.01'), Synset('`stock_car.n.02'), Synset('`subcompact.n.01'), Synset('`touring_car.n.01'), Synset('`used-car.n.01'), Synset('autom\xf3vil_de_vapor.n.01'), Synset('bote.n.03'), Synset('deportivo.n.01'), Synset('hardtop.n.01'), Synset('hatchback.n.01'), Synset('monovolumen.n.01'), Synset('taxi.n.01'), Synset('veh\xedculo_utilitario_deportivo.n.01')] 

---

Thanks so much!!

Xavier.

**Comment by luischir** [comment]
Hi,

Notice the hypernym synset says `motor_vehicle.n.01

It starts with a back quote, we use that to mark words that are not translated in the Spanish version of WordNet. The MCR is not complete, it has around half of the WordNet synsets translated to Spanish. In order to keep the ontology complete, we add at least one lemma for each synset, if there are no lemmas in the Spanish version, we use an English lemma prefixing it with a back quote (`) so we can tell apart which ones are not translated. The ones that don't have a back quote are taken from the Spanish MCR (WordNet).

Regards,
Luis

**Comment by xpoveda** [comment]
Perfect Luis, I understand.

Thank you for your great job!!

Xavier.
